/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tntela;

import DAO.AlunoDAO;
import DAO.Conexao;
import DAO.FuncionarioDAO;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.funcionario;

/**
 *
 * @author MANUEL GUSTAVO
 */
public class TelaAlterarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlterarFuncionario
     */
    public TelaAlterarFuncionario() {
        initComponents();
        setSize(690,350);
        setLocationRelativeTo(this);
    }
    
    private void InserirDados(int cod){
     
           Connection con = Conexao.AbrirConexao();
           FuncionarioDAO sql = new FuncionarioDAO(con);
           List<funcionario> lista = new ArrayList<>();
           lista = sql.CapturarFuncionario(cod);
           
           for (funcionario a : lista){
            
               jTF_Nome.setText(""+a.getNome());
               jTF_Senha.setText(""+a.getLogin());
               jTF_Email.setText("" + a.getSenha());
               
          }
        Conexao.FecharConexao(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTF_Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTF_Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_Senha = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTF_NomeFuncionario = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setText("ALTERAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 200, 150, 50);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("SAIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 200, 110, 20);

        jTF_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_NomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTF_Nome);
        jTF_Nome.setBounds(100, 140, 200, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("NOME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 140, 72, 39);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("EMAIL:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 140, 72, 39);
        getContentPane().add(jTF_Email);
        jTF_Email.setBounds(430, 140, 200, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("SENHA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 200, 72, 39);
        getContentPane().add(jTF_Senha);
        jTF_Senha.setBounds(100, 200, 200, 40);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("ALTERAR FUNCIONARIO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(19, 24, 310, 62);

        jButton1.setText("PROCURAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(547, 43, 100, 35);

        jLabel2.setText("CÓDIGO:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(337, 23, 57, 14);

        jTF_NomeFuncionario.setBackground(new java.awt.Color(0, 51, 51));
        jTF_NomeFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_NomeFuncionarioKeyPressed(evt);
            }
        });
        jPanel1.add(jTF_NomeFuncionario);
        jTF_NomeFuncionario.setBounds(337, 43, 204, 35);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 120);

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setText("VOLTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(520, 230, 110, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigo = jTF_NomeFuncionario.getText();
        Connection con = Conexao.AbrirConexao();
        FuncionarioDAO sql = new FuncionarioDAO(con);
        int cod = Integer.parseInt(codigo);
        if(sql.Testar_Funcionario(cod) == false){
            JOptionPane.showMessageDialog(null, "Código não encontrado no banco", "Carlos Alberto", JOptionPane.WARNING_MESSAGE);
        }

        jTF_Nome.setText("");
        jTF_Email.setText("");
        jTF_Senha.setText("");
        
        InserirDados(cod);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nome = jTF_Nome.getText();
        String email = jTF_Email.getText();
        String senha = jTF_Senha.getText();
        String iddd = jTF_NomeFuncionario.getText();
        if(nome.equals("") || email.equals("") || senha.equals("")){
            JOptionPane.showMessageDialog(null, "nenhum campo pode esta vazio", "Carlos Alberto", JOptionPane.WARNING_MESSAGE);

        }else{
            Connection con = Conexao.AbrirConexao();
            FuncionarioDAO sql = new FuncionarioDAO(con);
            funcionario a = new funcionario();
            
            int id = Integer.parseInt(iddd);
            a.setNome(nome);
            a.setLogin(email);
            a.setSenha(senha);
            a.setCod(id);
            
            sql.Alterar_Funcionario(a);
            Conexao.FecharConexao(con);

            jTF_Nome.setText("");
            jTF_Email.setText("");
            jTF_Senha.setText("");
            JOptionPane.showMessageDialog(null, "Alterado com Sucesso", "Carlos Alberto", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new tela1().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTF_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_NomeActionPerformed

    private void jTF_NomeFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_NomeFuncionarioKeyPressed
        
    }//GEN-LAST:event_jTF_NomeFuncionarioKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new telaCadFuncionario().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTF_Email;
    private javax.swing.JTextField jTF_Nome;
    private javax.swing.JTextField jTF_NomeFuncionario;
    private javax.swing.JTextField jTF_Senha;
    // End of variables declaration//GEN-END:variables
}
